runtime: java
env: flex
main: target/ejercicio-0.0.1.jar
service: nubel
#application: hello
#version: 1
entrypoint: "java -jar -noverify jercicio-0.0.1-SNAPSHOT.jar"
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

handlers:
- url:  /.*/
  script: auto
  secure: always
network:
  session_affinity: true

#script: this field is required, but ignored
#manual_scaling:
#  instances: 1
