runtime: java
env: flex
#application: hello
#version: 1
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

handlers:
- url:  /.*/
  script: auto
  secure: always
#  secure: always

#script: this field is required, but ignored
#manual_scaling:
#  instances: 1
env_variables:
  BUCKET_NAME: "example-gcs-bucket"
service: "springexample"
