runtime: java
env: flex
service: springexample-424021
#application: hello
#version: 1
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

handlers:
- url:  /.*/
  script: auto
  secure: always
network:
  session_affinity: true
#  secure: always
env_variables:
GOOGLE_APPLICATION_CREDENTIALS: 'my value'

#script: this field is required, but ignored
#manual_scaling:
#  instances: 1
